- name : Hello world deploy
  hosts: all
  become: yes
  tasks: 
    - name: install nginx
      dnf:
        name: nginx
        state: present
    - name: Create web page
      copy:
        content: "<h1>Hello World from Github Actions </h1>"
        dest: /usr/share/nginx/html/index.html
    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes