
name: "Terraform & Ansible CI/CD"
on:
  push:
    branches: ["master"] # master 브렌치에 
jobs:
  deploy:
    runs-on: ubuntu-latest # 최신 ubuntu 를 잠시 빌려서 아래 작업을 수행

    # mgmt 서버에서 aws configure를 실행해서 키를 등록했듯이 1회용 ubuntu 서버에도 동일한 작업
    # job 안의 모든 step 에서 등록된 aws 키를 공통으로 사용
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCEESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    step:
      # 1. 소스코드 체크아웃 ( gibhub 저장소를 clone하고 해당 폴더 안으로 들어가는 작업 대신 해줌)
      - uses: actions/checkout@v5
      
      # 2. terraform 환경 구성
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v4
      
      # 3. init & apply 실행
      - name: terraform init & apply
        run: |
          terraform init
          terraform apply --auto-approve  
      
      # 4. ansible 용 key setting ( github의 ubuntu의 ~/.ssh/id_rsa 파일에 key넣는 작업 )
      - name: setup ssh key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 5. ansible playbook실행
      - name: run ansible playbook
        run: |
      # terraform이 이미 inventory.yml과 ansible.cfg를 현재 디렉토리에 만들어 놓음.
          ansible-playbook nginx_setup.yml    