name: "Terraform & Ansible CI/CD"
on:
  push:
    branches: ["master"] # master 브렌치에 push 가 될때마다 실행하겠다는 의미
jobs:
  deploy:
    runs-on: ubuntu-latest # 최신 ubuntu machine 을 잠시 빌려서 아래의 작업을 수행해겠다는 의미
    # unbuntu machine 의 환경변수에 넣어줄 값을 셋팅하는 설정
    # 우리가 mgmt 서버에  aws configure 를 실행해서 키를 등록했듯이  1 회용 ubuntu 서버에도 동일한 작업을 해준다
    # job 안의 모든 step 에서 등록된 aws 키를 공통으로 사용하게 된다.
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # 이게 동작하기 위해서는 github 에 secrets 가 등록이 되어 있어야한다
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      # 1. 소스코드 체크아웃
      - uses: actions/checkout@v5
     
      # 2. terraform 환경 구성
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v4
     
      # 3. init & apply 실행
      - name: terraform init & apply
        run: |
          terraform init
          terraform apply --auto-approve


      # 4. ansible 용 key setting
      - name: setup ssh key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      # 5. ansible playbook 실행
      - name: run ansible playbook
        run: |
          # terraform 이 이미 inventory.yml 과 ansible.cfg 를 현재 디렉토리에 만들어 놓았습니다.
          ansible-playbook nginx_setup.yml